[features]
seeds = false
skip-lint = false
[programs.localnet]
soliage = "JCrKhCHMnwwgGByjDntnADS7zmo22petbVYwumn8s2xf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./.keys/oracle_dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
